Repository oracle-terraform-modules/terraform-oci-oke, pull requests merged in 2023-07, with the labels that each got.

#760 docs: updated documentation for worker mode
  docs/src/guide/network.md
  docs/src/guide/topology.md
  docs/src/images/privateworkers-large.svg
  docs/src/images/privateworkers.svg
  docs/src/images/publicworkers-large.svg
  docs/src/images/publicworkers.svg
Labels: OCA Verified

#761 docs: completed topology section, reorganized navigation
  docs/src/SUMMARY.md
  docs/src/gs/intro.md
  docs/src/guide/oci_integrations.md
  docs/src/guide/topology.md
  docs/src/guide/ug.md
  docs/src/images/bastion-large.svg
  docs/src/images/bastion.svg
  docs/src/images/defaultmad-large.svg
  docs/src/images/defaultmad.svg
  docs/src/images/defaultsad-large.svg
  docs/src/images/defaultsad.svg
  docs/src/images/loadbalancers-large.svg
  docs/src/images/loadbalancers.svg
  docs/src/images/networking-large.svg
  docs/src/images/networking.svg
  docs/src/images/privatecluster-large.svg
  docs/src/images/privatecluster.svg
  docs/src/images/privateworkers-large.svg
  docs/src/images/privateworkers.svg
  docs/src/images/publiccluster-large.svg
  docs/src/images/publiccluster.svg
  docs/src/images/publicworkers-large.svg
  docs/src/images/publicworkers.svg
Labels: OCA Verified

#743 fix: Update link to Oracle Contributor Agreement
  CONTRIBUTING.md
Labels: OCA Verified

#764 fix: 5.x Disable unused datasources, create NSGs with auto defaults
  data-images.tf
  module-bastion.tf
  module-operator.tf
  modules/extensions/versions.tf
  modules/network/nsg-bastion.tf
  modules/network/nsg-controlplane.tf
  modules/network/nsg-fss.tf
  modules/network/nsg-loadbalancers-int.tf
  modules/network/nsg-loadbalancers-pub.tf
  modules/network/nsg-operator.tf
  modules/network/nsg-pods.tf
  modules/network/nsg-workers.tf
Labels: OCA Verified

#766 docs: improve formatting of examples/workers tfvars
  examples/workers/vars-workers-advanced.auto.tfvars
  examples/workers/vars-workers-autoscaling.auto.tfvars
  examples/workers/vars-workers-basic.auto.tfvars
  examples/workers/vars-workers-clusternetwork.auto.tfvars
  examples/workers/vars-workers-drain.auto.tfvars
  examples/workers/vars-workers-instance.auto.tfvars
  examples/workers/vars-workers-instancepool.auto.tfvars
  examples/workers/vars-workers-network-vnics.auto.tfvars
  examples/workers/vars-workers-nodepool.auto.tfvars
Labels: OCA Verified

#767 docs: improve formatting by putting more variables different lines
  examples/network/vars-network-subnets-create-force.auto.tfvars
  examples/profiles/network-only/main.tf
  examples/rms/oke-network-only/main.tf
Labels: OCA Verified

#772 fix: 5.x Use correct state_id var in resource tags
  module-bastion.tf
  module-cluster.tf
  module-network.tf
  module-operator.tf
Labels: bug, OCA Verified

#771 feat: 5.x Implement worker pool drain
  docs/src/guide/workers_drain.md
  examples/profiles/workers-only/main.tf
  examples/profiles/workers-only/variables.tf
  examples/workers/vars-workers-drain.auto.tfvars
  module-utilities.tf
  module-workers.tf
  modules/utilities/drain.tf
  modules/utilities/variables.tf
  modules/utilities/versions.tf
  modules/workers/locals.tf
  modules/workers/outputs.tf
  variables-utilities.tf
Labels: enhancement, OCA Verified

#779 fix: 5.x Unspecified default placement FDs when mode != virtual-node-pool
  modules/workers/instance.tf
  modules/workers/instanceconfig.tf
  modules/workers/instancepools.tf
  modules/workers/locals.tf
  modules/workers/nodepools.tf
  modules/workers/virtualnodepools.tf
Labels: OCA Verified

#781 feat: 5.x Implement node_eviction_node_pool_settings
  modules/workers/locals.tf
  modules/workers/nodepools.tf
Labels: enhancement, OCA Verified

#777 docs: Add clarifying examples for operator instance principal
  docs/src/guide/operator_identity.md
Labels: OCA Verified

#783 fix: missing lb rule so load balancers become healthy
  modules/network/nsg-workers.tf
Labels: OCA Verified
